project_id = "vyibhpzolpgsprfdjhps"

[functions.generate-business-model]
verify_jwt = false

[functions.generate-business-plan]
verify_jwt = false

[functions.generate-financial-table]
verify_jwt = false

[functions.analyze-cashflow]
verify_jwt = false

